stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    # Setup SSH deploy keys
    - "which ssh-agent || ( apt-get install -qq openssh-client )"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh egor@89.108.83.2 "cd /var/www/apps/smile-beta-front && git pull && yarn && yarn build && exit"
  only:
    - master
    - dev
