export const urls = {
    authLogin: () => `/api/auth/jwt/create/`,
    authLogout: () => `/api/auth/token/logout/`,
    me: () => `/api/auth/users/me/`,
    students: () => '/api/profiles/',
    studentById: (id: string | number) => `/api/profiles/${id}/`,
    projects: () => '/api/projects/',
    projectsByCompany: (id: number | string) => `/api/projects/?company_id=${id}`,
    projectById: (id: string) => `/api/projects/${id}/`,
    projectByIdDonate: (id: number) => `/api/projects/${id}/donate/`,
    tags: (keyword: string) => `/api/tags/?keyword=${keyword}`,
    filterStudents: (tagsIds: string) => `/api/profiles?tags=${tagsIds}`,
    reviews: (id: string) => `/api/reviews/?student=${id}`,
    createReview: () => `/api/reviews/`,
    invites: (id: string, initiator: string) => `/api/student_requests/?id=${id}&initiator=${initiator}`,
    companyById: (id: string) => `/api/companies/${id}/`,
    makeRequest: (id: number) => `/api/projects/${id}/request/`,
    decideRequest: (id: number) => `/api/student_requests/${id}/make_response/`,
    crowdfounding: () => '/api/crowdfounding/',
    crowdfoundingById: (id: string) => `/api/crowdfounding/${id}/`,
    profileInviteToProject: (id: string | number) => `/api/profiles/${id}/invite/`,
    randomPick: () => '/api/tinder/random_pick/',
    like: (id: string | number) => `/api/tinder/${id}/dislike/`,
    dislike: (id: string | number) => `/api/tinder/${id}/like/`,
    updateTags: (id: string | number) => `/api/student_requests/${id}/update_tags/`,


}
